# Generated by Django 3.1.3 on 2021-07-08 18:28

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210708_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.CharField(default=[0], max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
