# Generated by Django 3.1.3 on 2021-07-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210708_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
