# Generated by Django 3.1.3 on 2021-07-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
