# Generated by Django 3.1.3 on 2021-07-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210708_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='score',
        ),
    ]
